---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pks-cluster-api
  labels:
    app: pks-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pks-api
  template:
    metadata:
      labels:
        app: pks-api
    spec:
      containers:
      - name: pks-cluster-api
        image: gcr.io/cf-london-servces-k8s/pks-cluster-api:latest
        ports:
        - containerPort: 8443
        env:
        - name: GCP_PROJECT
          value: "<<redacted>>"
      serviceAccountName: pks-cluster-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pks-cluster-api
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-api
rules:
# - apiGroups: [""]
#   resources: ["namespaces"]
#   verbs: ["create","delete"]
- apiGroups: ["cluster.k8s.io"]
  resources: ["clusters", "machines"]
  verbs: ["create","delete"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-api
rules:
- apiGroups: [""]
  resources: ["namespaced"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pks-cluster-api-namespaces
roleRef:
  kind: ClusterRole
  name: cluster-api
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: pks-cluster-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pks-cluster-api-cluster-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-api
subjects:
- kind: ServiceAccount
  name: pks-cluster-api
---
kind: Service
apiVersion: v1
metadata:
  name: pks-api
spec:
  type: LoadBalancer
  selector:
    app: pks-api
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
